### ISSUE TITLE
01.04.OWS.GetCapabilities-Exceptions.5 - xpath

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#1]
Runing one test **01.04.OWS.GetCapabilities-Exceptions** generates this error:

Fatal Error: Error in call to extension function {public synchronized void com.occamlab.te.TECore.callTest(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo,java.lang.String) throws java.lang.Exception}: Exception in extension function java.lang.NullPointerException; SystemID: file:/Users/lbermudez/teamengine/TE_BASE/work/_Users_lbermudez_teamengine_TE_BASE_scripts_sos_2.0.0_ctl_SOS_ETS.xml/sos$Main.test; Line#: 2760; Column#: -1

Jul 17, 2014 12:27:46 PM com.occamlab.te.TECore executeTest
SEVERE: Error in call to extension function {public synchronized void com.occamlab.te.TECore.callTest(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo,java.lang.String) throws java.lang.Exception}: Exception in extension function java.lang.NullPointerException
; SystemID: file:/Users/lbermudez/teamengine/TE_BASE/work/_Users_lbermudez_teamengine_TE_BASE_scripts_sos_2.0.0_ctl_SOS_ETS.xml/sos$Main.test; Line#: 2760; Column#: -1

net.sf.saxon.trans.XPathException: Error in call to extension function {public synchronized void com.occamlab.te.TECore.callTest(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo,java.lang.String) throws java.lang.Exception}: Exception in extension function java.lang.NullPointerException

**Comment by rjmartell** [comment]
I was unable to reproduce this. When I chose "Run selected tests" and the "01.OWS Main" group, the only failing test I saw is `ows-OWS.GetCapabilities-AcceptFormats.1`:

FAILURE: Unexpected content type for response entity (Request: application/xml, Response: application/soap+xml;charset=UTF-8).

It looks like the script doesn’t recognize a SOAP response as an XML entity. No exceptions appeared in the teamengine log file.

![sos-2 0-results](https://cloud.githubusercontent.com/assets/1653506/3629893/51f8f058-0ea5-11e4-98b5-d556f7bc1354.png)

**Comment by rockygis** [comment]
Test name : owsTests:ows-OWS.GetCapabilities-AcceptFormats.1

ctl:assertion

```
  The response to a GetCapabilities request containing an AcceptFormats

  parameter specifying a supported format must include a response entity

  that corresponds to the requested media type.
```

/ctl:assertion

The request acceptFormats : application/xml (Come from Capabilities).

The response content-type : application/soap+xml;charset=UTF-8

So the result is fail.

---

Tsung-Yen Lee (Rocky)
assistant software engineer
GIS Research Center, Feng-Chia University Taiwan
[描述: joinFB]http://www.facebook.com/GIS.FCU
