### ISSUE TITLE
SOS 2.0 Test Suite sos:IRTRequestInvalidobservationType test fails for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#10]
The sos:IRTRequestInvalidobservationType test fails for SOAP because the
request is invalid.
The element 'OM_GeometryObservation' is not valid to the specification.
[Originally reported in the OGC CITE issue tracker: issue #750](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=750)  

_Opened: 2012-12-21 05:45:21_

**Comment by rockygis** [comment]
The request in the sos:IRTRequestInvalidobservationType test doesn't send request which contain "OM_GeometryObservation" element. 
There are some issues about InsertResultTemplate, so we temporarily hide the test.
