### ISSUE TITLE
SOS 2.0 Test Suite sos:IRTRequestValidRequest test fails for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#11]
The sos:IRTRequestValidRequest test fails for SOAP fails because the href
value for featureOfInterest is empty.
[Originally reported in the OGC CITE issue tracker: issue #751](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=751)  

_Opened: 2012-12-21 05:46:28 Last Updated: 2012-12-21 05:52:54_

**Comment by rockygis** [comment]
The href value of featureOfInterest is from $getObservationResponse//om:featureOfInterest[1]/@xlink:href.
Maybe the response of getObservation is empty or error,so that the href value of featureOfInterest is empty.
There are some issues about InsertResultTemplate, so we temporarily hide the test.
