### ISSUE TITLE
SOS 2.0 Test Suite sos:IRRequestValidRequest test fails for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#13]
The sos:IRRequestValidRequest test fails for SOAP because there are two
stylesheet errors.
[Originally reported in the OGC CITE issue tracker: issue #753](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=75
3)  

_Opened: 2012-12-21 05:53:55_

**Comment by rockygis** [comment]
There are some issues about InsertResult, so we temporarily hide the test.
