### ISSUE TITLE
SOS 2.0 Test Suite sos:IRTRequestInvalidproposedTemplate test fails for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#14]
The  sos:IRTRequestInvalidproposedTemplate test fails for SOAP because the
href value for the featureOfInterest is missing.
[Originally reported in the OGC CITE issue tracker: issue #754](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=75
4)  

_Opened: 2012-12-21 05:54:49_

**Comment by rockygis** [comment]
The href value for the featureOfInterest is got from 
$getObservationResponse//om:featureOfInterest[1]/@xlink:href .
Maybe it is empty or no such element.
And,  there are some issues about InsertResultTemplate, so we temporarily hide the test.
