### ISSUE TITLE
spatial sampling feature from the O&M spec was missing in the SOS_ETS.xml

### ISSUE THREAD

**Issue by epicureanism** [opengeospatial/ets-sos20#16]
<ctl:test name="sos:GetObservation-Test"><xsl:when test="$isGET eq 'true'">
                                Line 3901 should add: <parsers:schema type="url">http://schemas.opengis.net/samplingSpatial/2.0/spatialSamplingFeature.xsd/parsers:schema

<ctl:test name="sos:GORequestOtherResponseFormat_core"><xsl:when test="$isGET eq 'true'">
                                Line 6082 should add: <parsers:schema type="url">http://schemas.opengis.net/samplingSpatial/2.0/spatialSamplingFeature.xsd/parsers:schema   

<ctl:test name="sos:GORequestEmptyObservation_core"><xsl:when test="$isGET eq 'true'">
                                Line 6220 should add: <parsers:schema type="url">http://schemas.opengis.net/samplingSpatial/2.0/spatialSamplingFeature.xsd/parsers:schema
                                Line 6212, 6215 should omit namespace: phenomenonTime has what looks like an om: namespace

Function:
<ctl:function name="sosFunctions:validateGetObservationResponse">
                Line 25404 should add: <parsers:schema type="url">http://schemas.opengis.net/samplingSpatial/2.0/spatialSamplingFeature.xsd/parsers:schema

**Comment by rockygis** [comment]
I have add  < parsers:schema type="url">http://schemas.opengis.net/samplingSpatial/2.0/spatialSamplingFeature.xsd< /parsers:schema> to every test of GetObservation.
And I have update to GitHub.
