### ISSUE TITLE
a namespace added to phenomenonTime in the sos:GORequestEmptyObservation_core shouldn't be there.

### ISSUE THREAD

**Issue by epicureanism** [opengeospatial/ets-sos20#17]
<ctl:test name="sos:GORequestEmptyObservation_core"><xsl:when test="$isGET eq 'true'">
                                Line 6220 should add: <parsers:schema type="url">http://schemas.opengis.net/samplingSpatial/2.0/spatialSamplingFeature.xsd/parsers:schema
                                Line 6212, 6215 should omit namespace: phenomenonTime has what looks like an om: namespace

**Comment by rockygis** [comment]
I have add namespace "xmlns:fes="http://www.opengis.net/fes/2.0" to < ctl:test name="sos:GORequestEmptyObservation_core"> (Line 6214)
And I have update to Github.
