### ISSUE TITLE
SOS 2.0 Test Suite GetObservation-Test fail for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#2]
The GetObservation-Tests fail for SOAP becuase there are validation errors:
cvc-elt.4.2: Cannot resolve 'ns:MeasureType' to a type definition for element
'om:result'.
But response is valid, checked with XmlBeans validation and with an external
validation tool.
[Originally reported in the OGC CITE issue tracker: issue #726](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=726)  
_Opened: 2012-12-13 10:19:50 Last Updated: 0000-00-00 00:00:00_

**Comment by rockygis** [comment]
The CTL xml validation cannot identify "ns:MeasureType".
We are trying to develop the test by the TestNG framework.
Maybe we can use TestNG to solve the issue.

**Comment by rockygis** [comment]
ns:MeasureType was defined in the gml, it should be loaded and identified in the CTL. If there is any XML file or URL for the tested O&M example, it will be much appreciated.

**Comment by dstenger** [comment]
@arieslai Can you please check the current status of this issue?

**Comment by dstenger** [comment]
TEAM Engine issue also tackles this problem: https://github.com/opengeospatial/teamengine/issues/210

**Comment by ghobona** [comment]
Closing this issue because it is tabled at https://github.com/opengeospatial/ets-sos20/issues/2
