### ISSUE TITLE
07.SOS enhancedOperations: GetObservationById - 07.09.RequestValidRequest Test - invalid test request for POST

### ISSUE THREAD

**Issue by agtokty** [opengeospatial/ets-sos20#20]
In Test Suite: SOS 2.0, teamengine sends a request with no observation id in Test sos:GOBIRequestValidRequest_obsByIdRetrieval  test.
Normally if sos:observation element does not have value(s) Sos server should throw an exception ( MissingParameterValue, locator=Observation).

According to **OGC 12-006** document , observation should be one or many (mandatory) .

See Table 29: Properties of GetObservationById data type in **OGC 12-006**

And here is my log : https://gist.github.com/agtokty/cde89879a2c3674dbbaf

**Comment by rockygis** [comment]
The observation is from "ows:OperationsMetadata/ows:Operation[@name='GetObservationById']/ows:Parameter[@name='observation']/ows:AllowedValues/ows:Value[1]" in the GetCapabilities response.
Teamengine got an empty string so it sends a request with empty observation id.

**Comment by rockygis** [comment]
It looks like the TeamEngine needs the observation id from the response body of GetCapabilities, but lacks of these info. If the observation id can be found in the GetCapabilities, this problem should be no problem.
