### ISSUE TITLE
08.SOS resultRetrieval: GetResultTemplate - 08.07.RequestNulloffering - invalid test request for POST

### ISSUE THREAD

**Issue by agtokty** [opengeospatial/ets-sos20#22]
Same issue like here https://github.com/opengeospatial/ets-sos20/issues/21

sos:offering element is expected to be null, but sos:observedProperty is null and offering has a valid value

test log from [teamengine](http://cite.opengeospatial.org/teamengine/)    :
https://gist.github.com/agtokty/a9e57dca519bc020b4fc

**Comment by rockygis** [comment]
Thank for your response.
We will fix it in next version and update to Github.
