### ISSUE TITLE
Add conformance class configuration into the ets-sos20 test

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-sos20#25]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
@epicureanism or @rockygis Can one of you configure the conformance classes for this test suite?

**Comment by rockygis** [comment]
"Basic Conformance Classes" Changed.
commit no : 674a0616ecd9f5a26646d5a2886dc9f5e90703fd

**Comment by dstenger** [comment]
@rockygis 
Thank you for your help.

However, the basic conformance class attributes must not be configured for each test but just for parent tests which collect all tests of one conformance class.

I updated the documentation to make it more clear: https://github.com/opengeospatial/teamengine/blob/master/src/site/markdown/encoding-conformance-classes.md

If you have further questions, you are welcome to contact me (in this issue).

**Comment by rockygis** [comment]
OK
I remarked the attributes.
commit no: de0a54a877ce6c51f0744a41f475a6671b27bd25

**Comment by dstenger** [comment]
Unfortunately, the configuration of conformance classes does not work.

Used service for testing: http://sensorweb.demo.52north.org/52n-sos-webapp/service?service=SOS&request=GetCapabilities&AcceptVersions=2.0.0

The new HTML report is not filled with values:

![ets-sos20-html-report](https://user-images.githubusercontent.com/2989166/40168367-99528668-59c3-11e8-9f0b-383b8e2986bd.png)

Old report:

![ets-sos20-old-report](https://user-images.githubusercontent.com/2989166/40168372-9ead02aa-59c3-11e8-97d9-8fca544a36aa.png)

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please support rockygis?

**Comment by keshavnangare** [comment]
@dstenger 

I have tested ETS on my local machine and its working, generated the HTML report. This issue is reproducible on beta environment. 
```
Teamengine : Current Master
ets-sos20 : 1.14-SNAPSHOT
OS : Windows 8.1
```
While generating the html report we get the error as similar to [ets-wcs20#67](https://github.com/opengeospatial/ets-wcs20/issues/67#issuecomment-390974716).

Can you please check weather it is working on your local machine or not?

**Comment by dstenger** [comment]
@keshav-nangare 

I tested this with [teamenine-docker](https://github.com/opengeospatial/teamengine-docker/tree/master/teamengine-ets-sos20) and the problem occurred.

On beta environment, this enhancement is not installed yet.

**Comment by keshavnangare** [comment]
@dstenger 

I have tested with the docker environment with sos20 [current_master] and got the issue similar to [ets-wcs20#67](https://github.com/opengeospatial/ets-wcs20/issues/67#issuecomment-390974716).

```
SEVERE: Transformation of EARL to HTML failed.
; SystemID: file:/usr/local/tomcat/webapps/teamengine/WEB-INF/classes/com/occamlab/te/earl_html_report.xsl; Line#: 318; Column#: -1
net.sf.saxon.trans.XPathException: A sequence of more than one item is not allowed as the first operand of '+'
```

The issue is with the earl report, this issue solved if we fixed the issue from opengeospatial/ets-wcs20/issues/67

**Comment by lgoltz** [comment]
The problem occurred, cause the test sos:general-main is not configured as conformance class. Currently all test on the same hierarchy level must be configured as  conformance class. 
Fixed with https://github.com/opengeospatial/ets-sos20/commit/6e646fe4169a56c32c70d0aa0aa61c43cd113daf on master

**Comment by lgoltz** [comment]
@keshav-nangare Can you check if the failure still occurs? Please close this issue if the report is shown as expected.

**Comment by keshavnangare** [comment]
@lgoltz 

I have successfully tested the changes and the new HTML report is generated.
