### ISSUE TITLE
SOS 2.0 Test Suite InsertSensor-Test fail for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#3]
The GetObservation-Tests fail for SOAP becuase there are validation errors:
cvc-elt.4.2: Cannot resolve 'ns:MeasureType' to a type definition for element
'om:result'.
But response is valid, checked with XmlBeans validation and with an external
validation tool.
[Originally reported in the OGC CITE issue tracker: issue #726](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=726)  
_Opened: 2012-12-13 10:19:50 Last Updated: 0000-00-00 00:00:00_

**Comment by rockygis** [comment]
The CTL xml validation cannot identify "ns:MeasureType".
We are trying to develop the test by the TestNG framework.
Maybe we can use TestNG to solve the issue.
