### ISSUE TITLE
Create SoapUI tests and integrate them into Maven and Jenkinsfile

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-sos20#32]
https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI

**Comment by lgoltz** [comment]
@keshav-nangare PR #37 must be merged first

**Comment by keshavnangare** [comment]
Merged this #37 PR branch(restApiFailed-36) to feature-issue#32 branch and created the fix.

Fixed with this commit: 1ecd122
