### ISSUE TITLE
Test "GFOIRequestInvalidSpatialFilter_foiRetrieval" fails with InvocationTargetException

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-sos20#33]
Tested with http://sensorweb.demo.52north.org/52n-sos-webapp/service?service=SOS&request=GetCapabilities&AcceptVersions=2.0.0 on a local docker environment.

Selected GET and all tests.

From the test report:
```
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) 
throws java.lang.Throwable}: Exception in extension function java.lang.reflect.InvocationTargetException
```

And the error log:

```
Caused by: java.lang.RuntimeException: Failed to parse resource from http://sensorweb.demo.52north.org/52n-sos-webapp/service/kvp?service=SOS&version=2.0.0&request=GetFeatureOfInterest&spatialFilter=2019-04-24T13:33:05.181Z
                        ,0.0,10.0,0.0,10.0,urn:ogc:def:crs:EPSG::4326 
 null
	at com.occamlab.te.parsers.XMLValidatingParser.parse(XMLValidatingParser.java:227)
	... 604 more
```

Request send by the test: `http://sensorweb.demo.52north.org/52n-sos-webapp/service/kvp?request=GetFeatureOfInterest&service=SOS&spatialFilter=2019-04-24T13:33:05.181Z                            ,0.0,10.0,0.0,10.0,urn:ogc:def:crs:EPSG::4326                            &version=2.0.0`

**Comment by dstenger** [comment]
@keshav-nangare Can you please do a short test of this fix?
