### ISSUE TITLE
Test "owsTests:ows-main" failed validation error via REST API 

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-sos20#35]
iut: http://sensorweb.demo.52north.org/52n-sos-webapp/service/kvp?service=SOS&request=GetCapabilities

**Comment by lgoltz** [comment]
@keshav-nangare Is this a duplicate of #36 ?

**Comment by keshavnangare** [comment]
@lgoltz  Thank you!

Yes, its duplicate so I will close this issue.
