### ISSUE TITLE
SOS 2.0 Test Suite InsertSensor-Test fail for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#4]
InsertSensor-Test fail for SOAP because:
- Nearly all tests send an InvalidRequest because in 'SensorML' the' version' attribute and the 'member' element is missing
- ISRequestValidRequest failed because Stylsheet. 2 errrors detected.

[Originally reported in the OGC CITE issue tracker: issue #731](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=731)  
_Opened: 2012-12-13 10:29:40

**Comment by rockygis** [comment]
In the test of the InsertSensor, there is 'version' attribute and  'member' element.
And I don't see any stylesheet error.
Maybe you can give me more log about the test.

There are some issues about InsertSensor, so we temporarily hide the test.
