### ISSUE TITLE
REST interface responds differently on local installation and Beta environment

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-sos20#40]
If following request is sent against Beta environment, 12 tests pass and 0 fail the test suite.

https://cite.opengeospatial.org/te2/rest/suites/sos20/run?service-url=http://sensorweb.demo.52north.org/52n-sos-webapp/service?service=SOS&request=GetCapabilities&AcceptVersions=2.0.0

However, if the same request is sent against a local setup (Docker Image) of the master branch, 88 tests pass and 10 fail the test suite (is also executed by integration-tests).

http://localhost:8081/teamengine/rest/suites/sos20/run?service-url=http://sensorweb.demo.52north.org/52n-sos-webapp/service?service=SOS&request=GetCapabilities&AcceptVersions=2.0.0

Why are both environments behaving differently, although they should return the same result?

**Comment by dstenger** [comment]
@dstenger will provide all libraries which are installed on Beta environment to @keshav-nangare so that he can do further analysis.

**Comment by keshavnangare** [comment]
@dstenger

Following is the workaround:
1. When the test suite executed on beta environment containing jar of all test suites, the xsd's are mentioned in tests are picked from the sensorml20 jar. The loading path and thrown exception are in error [log.txt](https://github.com/opengeospatial/ets-sos20/files/5781191/log.txt) file.
2. When the test suite executed on docker environment, there is only sos20 jar is present so it runs all tests.

**Possible Solution**
1. The xsd loading from sensorml20 jar is having encoding UTF-16, can be changed to UTF-8.(Fix can be added to ets-sensorml20)

OR

2. Changed the directory of xsd file in sos20 test suite and its references in the tests(Fix can be added to ets-sos20).

**Comment by dstenger** [comment]
@keshav-nangare Please implement solution 1: Updating of the encoding of the XSD.

**Comment by keshavnangare** [comment]
I have created an [issue](https://github.com/opengeospatial/ets-sensorml20/issues/54) and fixed it by updating the encoding of file in the sensorml20 test suite.

**Comment by dstenger** [comment]
Associated pull request was merged.
