### ISSUE TITLE
SOS 2.0 Test Suite InsertObservation-Test fail for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#5]
InsertObservation-Test fail for SOAP because:
- IORequestNoService, -NullService, -InvalidService, -NoVersion, -NullVersion, -InvalidVersion, -Nulloffering,-Invalidoffering failed because the request is invalid, OM_Observation element is missing.
- IORequestNullobservationType, -InvalidobservationType, -Nullprocedure, -Invalidprocedure, -NullobservedProperty, -InvalidObservedProperty, -NullfeatureOfInterest, -InvalidfeatureOfInterest failed because the request is invalid, 'uom' attribute is missing in om:result with xsi:type="gml:MeasureType".
- IORequestNullresultType, -InvalidresultType failed because the request is invalid
- IORequestValidRequest failed because of Stylesheet. 3 errors detected.
  [Originally reported in the OGC CITE issue tracker: issue #732](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=73
  2)  

_Opened: 2012-12-13 10:30:48 Last Updated: 2012-12-13 10:35:20_

**Comment by rockygis** [comment]
There are some issues about InsertObservation, so we temporarily hide the test.
