### ISSUE TITLE
SOS 2.0 Test Suite InsertResultTemplate-Test fail for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#6]
InsertResultTemplate-Test fail for SOAP because:
- All tests send an InvalidRequest because the 'href' value in the 'featureOfInterest' element is empty.

[Originally reported in the OGC CITE issue tracker: issue #733](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=73
3)  

_Opened: 2012-12-13 10:31:27 Last Updated: 2012-12-13 10:35:03_

**Comment by rockygis** [comment]
There are some issues about InsertResultTemplate, so we temporarily hide the test.
