### ISSUE TITLE
SOS 2.0 Test Suite sos:GOBIRequestValidRequest test fails for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#7]
The GOBIRequestValidRequest test fails for SOAP if the test does not set an
observation value.
A solution could be to look in the OperationsMetadata for the
GetObservationById, if exists, if there are valid values listed.
[Originally reported in the OGC CITE issue tracker: issue #747](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=747)  

_Opened: 2012-12-21 05:34:58 Last Updated: 2013-10-31 10:21:56_

**Comment by rockygis** [comment]
The observation is got from ows:OperationsMetadata/ows:Operation[@name='GetObservationById']/ows:Parameter[@name='observation']/ows:AllowedValues/ows:Value[1].
Maybe it is empty or no such element.

**Comment by rockygis** [comment]
It looks like the TeamEngine needs the observation id from the response body of GetCapabilities, but lacks of these info. If the observation id can be found in the GetCapabilities, this problem should be no problem.
