### ISSUE TITLE
SOS 2.0 Test Suite sos:ISRequestValidRequest  test fails for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#8]
The sos:ISRequestValidRequest  test fails for SOAP because the check for the
'assignedOffering' is invalid.
See difference between this check and the check for the 'assignedProcedure'.

[Originally reported in the OGC CITE issue tracker: issue#748](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=748)  

_Opened: 2012-12-21 05:37:59 Last Updated: 0000-00-00 00:00:00_

**Comment by rockygis** [comment]
We fixed the error.
Now, the check for the 'assignedOffering' is 
xsl:variable name="assignedOfferingCount " select="count($InsertSensorResponse//swes:InsertSensorResponse//swes:assignedOffering)" 

There are some issues about InsertSensor, so we temporarily hide the test.
