### ISSUE TITLE
SOS 2.0 Test Suite sos:DeSRequestValidRequest  test fails for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#9]
The sos:DeSRequestValidRequest  test fails for SOAP because there is a
stylesheet error.
[Originally reported in the OGC CITE issue tracker: issue #749](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=749)  

_Opened: 2012-12-21 05:39:07_

**Comment by rockygis** [comment]
I don't find any stylesheep error when i test sos:DeSRequestValidRequest, maybe you can show me more detail or log about the error.
There are some issues about DeleteSensor, so we temporarily hide the test.
